/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SkillsSlugRouteImport } from './routes/skills.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTokensRouteImport } from './routes/admin.tokens'
import { Route as AdminSyncRouteImport } from './routes/admin.sync'
import { Route as AdminSkillsRouteImport } from './routes/admin.skills'
import { Route as AdminRbacRouteImport } from './routes/admin.rbac'
import { Route as AdminAuthRouteImport } from './routes/admin.auth'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTokensRoute = AdminTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSyncRoute = AdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRbacRoute = AdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/publish': typeof PublishRoute
  '/search': typeof SearchRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/users': typeof AdminUsersRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/publish': typeof PublishRoute
  '/search': typeof SearchRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/users': typeof AdminUsersRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/publish': typeof PublishRoute
  '/search': typeof SearchRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/users': typeof AdminUsersRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/publish'
    | '/search'
    | '/admin/auth'
    | '/admin/rbac'
    | '/admin/skills'
    | '/admin/sync'
    | '/admin/tokens'
    | '/admin/users'
    | '/skills/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/publish'
    | '/search'
    | '/admin/auth'
    | '/admin/rbac'
    | '/admin/skills'
    | '/admin/sync'
    | '/admin/tokens'
    | '/admin/users'
    | '/skills/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/publish'
    | '/search'
    | '/admin/auth'
    | '/admin/rbac'
    | '/admin/skills'
    | '/admin/sync'
    | '/admin/tokens'
    | '/admin/users'
    | '/skills/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PublishRoute: typeof PublishRoute
  SearchRoute: typeof SearchRoute
  SkillsSlugRoute: typeof SkillsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tokens': {
      id: '/admin/tokens'
      path: '/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AdminTokensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sync': {
      id: '/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AdminSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skills': {
      id: '/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rbac': {
      id: '/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AdminRbacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuthRoute: typeof AdminAuthRoute
  AdminRbacRoute: typeof AdminRbacRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminSyncRoute: typeof AdminSyncRoute
  AdminTokensRoute: typeof AdminTokensRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthRoute: AdminAuthRoute,
  AdminRbacRoute: AdminRbacRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminSyncRoute: AdminSyncRoute,
  AdminTokensRoute: AdminTokensRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PublishRoute: PublishRoute,
  SearchRoute: SearchRoute,
  SkillsSlugRoute: SkillsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
